dbt_start:
    target: dev
    outputs:
      dev:
        type: snowflake
        account: AB64685.eu-west-2.aws

        user: CHRISTOPHEKEVERS
        password: Kokomo007&

        role: PC_DBT_ROLE
        database: PC_DBT_DB
        warehouse: PC_DBT_WH
        client_session_keep_alive : False
        schema: DBT_CKEVERS